version: '3.9'

services:
  openaibot:
    image: aiastia/moegoe:main
    command: python3 server.py
    volumes:
      - ./:/app
    networks:
      - app-tier
  

networks:
  app-tier:
    driver: bridge
